config/routes.rb
Rails.application.routes.draw do
  
  root 'projects#index'
  
  resources :projects, only: [:index, :create, :new, :show] do
    resources :pledges 
  end
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :projects
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
	belongs_to :project
	belongs_to :user
	belongs_to :reward
end

app/models/project.rb
class Project < ActiveRecord::Base

	has_many :rewards
	has_many :pledges
  belongs_to :user
	belongs_to :category
	accepts_nested_attributes_for :rewards, :reject_if => :all_blank, :allow_destroy => true
	has_attached_file :image, styles: { 
		small: "64x64", 
		med: "250x250", 
		large: "600x600" 
	}
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	def amount_remaining
		# VERSION 1
		# sum = 0

		# pledges.each do |pledge|
		# 	sum += pledge.contribution
		# end

		# VERSION 2a
		# sum = pledges.inject(0) { |sum, pledge| sum + pledge.contribution }

		# VERSION 2b
		# return funding_goal - pledges.inject(0) { |sum, pledge| sum + pledge.contribution }

		# VERSION 3
		funding_goal - total_raised
	end

	def total_raised
		pledges.sum(:contribution)
	end

	def progress
		(total_raised / funding_goal.to_f) * 100
	end 
end

app/models/reward.rb
class Reward < ActiveRecord::Base
	belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :projects
	has_many :rewards, through: :projects
	has_many :pledges, through: :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Please log in"
  		redirect_to new_session_path
  	end
  end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
	def new
    @project = load_project
    @pledge = @project.pledges.build
  end

	def create
    @project = load_project
    @reward = @project.rewards.find(params[:reward_id])
    @pledge = @project.pledges.new(reward: @reward, user: current_user, contribution: @reward.amount)

    respond_to do |format|
      if @pledge.save
        format.html { redirect_to project_path(@project.id), notice: "Pledged #{ActionController::Base.helpers.number_to_currency @reward.amount}" }
        format.js
      else
        raise
        format.html { render 'rootpath', alert: 'There was an error' }
      end
    end
  end

private
  def load_project
    @project = Project.find(params[:project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  	@project = Project.all
  end

  def new
  	@project = Project.new
  	@project.rewards.build
  end

  def create
  	@project = Project.new(project_params);
  	if @project.save
  		redirect_to projects_url
  	else
  		render 'new'
  	end
  end

  def show
    @project = Project.find(params[:id])
  end

  private
  def project_params
  	params.require(:project).permit(:name, :description, :category_id, :funding_goal, :start_at, :end_at, :image, rewards_attributes: [:id, :description, :amount, :_destroy])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
	def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render 'projects/index'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to projects_url, notice: "Signed up & Logged In!!!!"
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :address, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrowdFunder</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#">CrowdFunder</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
          <li><%= link_to 'Home', "/projects" %></li>
	        <li><%= link_to 'Add New', "/projects/new" %></li>
	      </ul>


	      <% if current_user %>
            <p class="navbar-text navbar-right">
              Signed in as 
                <%= current_user.email %>
                <p class="navbar-text navbar-right">
                  <%= link_to "Log out", session_path("current"), :method => :delete %>
                </p>
            </p>
          <% else %>
            <%= form_tag sessions_path, method: "POST", class: "navbar-form navbar-right" do |f| %>
              <div class="form-group">
                <%= text_field_tag :email, params[:email], class: "form-control", placeholder: "Email" %>
              </div>
              <div class="form-group">
                <%= password_field_tag :password, "", class: "form-control", placeholder: "Password" %>
              </div>
              <%= submit_tag "Log in", class: "btn btn-default" %>            
              <a href="/users/new" class="btn btn-primary">Sign Up</a>
            <% end %>
          <% end %>

          <% if flash[:notice] %>
            <script>
              $(document).ready(function(){
                swal({ 
                  title: "Awesome!",   
                  text: '<%= j flash[:notice] %>',
                  type: "success",   
                  confirmButtonText: "Continue" 
                });
              });
            </script>
          <% end %>

          <% if flash[:alert] %>
            <p class="navbar-text navbar-left" id="alert">
              <%= flash[:alert] %>
            </p>
          <% end %>


	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->

	</nav><br><br>

 
    <br>
    <br>
      <%= yield %>

</body>
</html>

app/views/projects/_reward_fields.html.erb
<div class="col-lg-3 col-sm-6 nested-fields">
  <div>
  <%= f.text_field :title, placeholder: "Title" %>
  </div><br>
  <div>
    <%= f.text_area :description, placeholder: "Description" %>
  </div><br>
  <div>
    <%= f.text_field :amount, placeholder: "Amount" %>
  </div><br><hr/>
</div>

app/views/projects/index.html.erb
<% if current_user %>
	<h1 style="color:white;" class="text-center">All Currently Open Projects</h1>
	<% @project.each do |p| %>
		<div class="panel panel-info col-lg-3 col-md-4 col-sm-4 col-xs-12 text-center">
			<div class="panel-heading">
				<h4><u><%= p.name %></u></h4>
			</div>
			<div class="panel-body">
				<div class="center"><%= image_tag p.image.url(:small) %></div><hr />
				<div class="progress">
  				<div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= p.progress %>%">
    				<%= p.progress.to_i %>% Funded
  				</div>
				</div>
				<%= link_to 'Show Details', "/projects/#{p.id}", class: "btn btn-default" %>
			</div>
		</div>
	<% end %>

<% else %>
	
	<!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>CrowdFunder welcomes u :)</h1>
        <p>This website was designed and built for you..... literally for you. You post up a project and 
        let the people decide if they think it's worth it to donate</p>
        <p><a class="btn btn-primary btn-lg" href="users/new" role="button">Sign up now &raquo;</a></p>
      </div>
    </div>

    <div class="container well">
      <div class="row">
        <div class="col-md-4">
          <h2>Purpose</h2>
          <p>This app is used to attempt funding on a project of your choice.</p>
        </div>
        <div class="col-md-4">
          <h2>Get Started Today</h2>
          <p>To start actually using this application, you need to sign up. It's very straight forward and simple to understand, and i promise no request for credit cards will be present during the signup process.</p>
          <%= link_to 'Get Started', "/users/new", class: "btn btn-default" %>
       </div>
        <div class="col-md-4">
          <h2>Awesomeness</h2>
          <p>This app has alot of features that allow a regular average joe to recieve funding on a project of his/her interest or desire.</p>
        </div>
      </div>
<% end %>

app/views/projects/new.html.erb
<div class="text-center container well">
	<% if current_user %>
		<h1 class="text-center">Create a new project</h1>
		<%= form_for @project, html: { multipart: true } do |f| %>
			<form>
				<div>
					<%= f.text_field :name, placeholder: "Project Name" %>
				</div><br>
				
				<div style="margin-left: 40%;">
					<%= f.file_field :image %>
				</div>
				
				<div>
					<%= f.select :category_id, Category.all.map{|c| [c.name, c.id]} %>
				</div><br>
				
				<div>
					<%= f.text_area :description, placeholder: "Project Description" %>
				</div>

				<h2>Rewards</h2>
				<%= f.fields_for :rewards do |rewards_form| %>
					<% 8.times do |n| %>
						<%= render 'reward_fields', f: rewards_form %>
					<% end %>
				<% end %>

				<div class="">
					<%= f.submit %>
				</div>

			</form>
		<% end %>
	<% else %>
		<h1 class="text-center">Please log in to make a new project </h1>
	<% end %>
</div>

app/views/projects/show.html.erb
<% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
  <p id="alert"><%= flash[:alert] %></p>
<% end %>

<div class="well clearfix text-center">
	<h1>Details Page</h1><hr />
	
	<div class="thumbnail" style="background-color: grey;">
		<h1><%= @project.name %></h1>
		<%= image_tag @project.image.url(:med) %>
	</div>

	
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">Description</h3>
		</div>
		<div class="panel-body">
			<%= @project.description %><br>
			Funding Goal: <%= number_to_currency @project.funding_goal %><br>
			Remaining Amount: <%= number_to_currency @project.amount_remaining %>
			<div class="progress">
  			<div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= @project.progress %>%">
    			<%= @project.progress.to_i %>% Complete
  			</div>
			</div>
		</div>
	</div>
	
	<%= render @project.rewards %>

</div>

app/views/rewards/_reward.html.erb
<div class="col-lg-6 text-center">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h4><%= reward.title %></h4>
		</div>
		<div class="panel-body">
			<%= reward.description %>
			<p>Pledge: <%= number_to_currency reward.amount %></p>
		</div>
		<span class="pledge-button">
			<%= button_to 'Make Donation', 
				project_pledges_path(@project, :reward_id => reward.id), 
				:method => 'post',
				class: "btn btn-default" %>
		</span>
		<br>
	</div>
</div>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-lg-4 col-offset-2">

  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
     <div class="field">
      <%= f.label :first_name %><br/>
      <%= f.text_field :first_name, :class => "form-control" %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br/>
      <%= f.text_field :last_name, :class => "form-control" %>
    </div>
    <div class="field">
      <%= f.label :email %><br/>
      <%= f.text_field :email, :class => "form-control" %>
    </div>
    <div class="field">
      <%= f.label :address %><br/>
      <%= f.text_field :address, :class => "form-control" %>
    </div>
    <div class="field">
      <%= f.label :password %><br/>
      <%= f.password_field :password, :class => "form-control" %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br/>
      <%= f.password_field :password_confirmation, :class => "form-control" %>
    </div>
    <br>
    <div class="actions"><%= f.submit %></div>
  <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="well text-center">
<h1>New User</h1>

<p>Already registered? Use the log-in form in the navigation bar above.</p>

<%= render 'form' %>
</div>